/*
 * Sales exports — PDF, Excel (xlsx), and CSV generated by backend code from normalized SAP data.
 * The LLM never produces export content. Documents live in memory for EXPORT_TTL_MS and are fetched by id.
 */
import { randomUUID } from "node:crypto";
import { deflateRawSync } from "node:zlib";
import { statusLabel } from "./salesAnalytics.service";
import type { StructuredView } from "./salesPlanner.service";
import { sumAmountsByCurrency, sumQuantities, type SalesItemRecord } from "./sapSales.service";

export type ExportFormat = "pdf" | "xlsx" | "csv";

/*
 * Export sheet interface.
 */
export interface ExportSheet {
  name: string;
  columns: string[];
  rows: Array<Array<string | number>>;
}

export interface ExportDocument {
  title: string;
  period: string;
  source: string;
  retrievedAt: string;
  kpis: Array<{ label: string; value: string }>;
  bullets: string[];
  note?: string;
  tables: Array<{ title: string; columns: string[]; rows: string[][] }>;
  sheets: ExportSheet[];
  csv: ExportSheet;
}

const EXPORT_TTL_MS = 30 * 60 * 1000;
const MAX_EXPORTS = 200;
const store = new Map<string, { doc: ExportDocument; expires: number }>();

function isoDate(date: Date | null): string {
  return date ? date.toISOString().slice(0, 10) : "";
}

function orderSheet(records: SalesItemRecord[]): ExportSheet {
  const byOrder = new Map<string, SalesItemRecord[]>();
  for (const record of records) {
    const bucket = byOrder.get(record.SalesOrder) ?? [];
    bucket.push(record);
    byOrder.set(record.SalesOrder, bucket);
  }
  const rows: Array<Array<string | number>> = [];
  for (const [order, items] of byOrder) {
    const quantities = sumQuantities(items);
    const quantity: string | number =
      quantities.length === 1 ? Math.round(quantities[0].quantity * 1000) / 1000 : quantities.map((entry) => `${entry.quantity} ${entry.unit}`).join(", ");
    for (const amount of sumAmountsByCurrency(items)) {
      rows.push([
        order,
        isoDate(items[0].CreationDate),
        items.length,
        quantity,
        quantities.map((entry) => entry.unit).join(", "),
        Math.round(amount.amount * 100) / 100,
        amount.currency,
        [...new Set(items.map((item) => item.Plant).filter(Boolean))].join(" "),
        [...new Set(items.map((item) => statusLabel(item.DeliveryStatus)))].join(", "),
        [...new Set(items.map((item) => statusLabel(item.BillingStatus)))].join(", "),
      ]);
    }
  }
  rows.sort((left, right) => String(left[0]).localeCompare(String(right[0])));
  return { name: "Sales Orders", columns: ["Sales Order", "Created", "Items", "Quantity", "Unit", "Net Amount", "Currency", "Plant", "Delivery Status", "Billing Status"], rows };
}

function itemSheet(records: SalesItemRecord[]): ExportSheet {
  return {
    name: "Sales Items",
    columns: ["Sales Order", "Item", "Created", "Time", "Material", "Plant", "Quantity", "Unit", "Net Amount", "Currency", "Customer Group", "Delivery Status", "Billing Status"],
    rows: records.map((record) => [
      record.SalesOrder,
      record.SalesOrderItem,
      isoDate(record.CreationDate),
      record.CreationTime,
      record.Material,
      record.Plant,
      record.OrderQuantity,
      record.OrderQuantityUnit,
      record.NetAmount,
      record.TransactionCurrency,
      record.CustomerGroup,
      statusLabel(record.DeliveryStatus),
      statusLabel(record.BillingStatus),
    ]),
  };
}

function trendSheet(records: SalesItemRecord[]): ExportSheet {
  const byDate = new Map<string, SalesItemRecord[]>();
  for (const record of records) {
    const key = isoDate(record.CreationDate);
    if (!key) continue;
    const bucket = byDate.get(key) ?? [];
    bucket.push(record);
    byDate.set(key, bucket);
  }
  const currencies = [...new Set(records.map((record) => record.TransactionCurrency).filter(Boolean))].sort();
  const units = [...new Set(records.map((record) => record.OrderQuantityUnit || "EA"))].sort();
  return {
    name: "Daily Trend",
    columns: ["Date", "Sales Orders", "Items", ...units.map((unit) => `Quantity ${unit}`), ...currencies.map((currency) => `Amount ${currency}`)],
    rows: [...byDate.entries()]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([date, items]) => {
        const amounts = sumAmountsByCurrency(items);
        const quantities = sumQuantities(items);
        return [
          date,
          new Set(items.map((item) => item.SalesOrder)).size,
          items.length,
          ...units.map((unit) => Math.round((quantities.find((entry) => entry.unit === unit)?.quantity ?? 0) * 1000) / 1000),
          ...currencies.map((currency) => Math.round((amounts.find((entry) => entry.currency === currency)?.amount ?? 0) * 100) / 100),
        ];
      }),
  };
}

export function buildExportDocument(view: StructuredView, records: SalesItemRecord[] = []): ExportDocument {
  const period = view.provenance?.period ?? "";
  const retrievedAt = view.provenance?.retrievedAt ?? view.updatedAt ?? new Date().toISOString();
  const tables = [
    ...(view.rows.length > 0 ? [{ title: view.title, columns: view.columns, rows: view.rows }] : []),
    ...(view.sections ?? []).map((section) => ({ title: section.title, columns: section.columns, rows: section.rows })),
  ];
  const summary: ExportSheet = {
    name: "Summary",
    columns: ["Field", "Value"],
    rows: [
      ["Report", view.title],
      ["Period", period],
      ["Source", "SAP Sales API (ZI_SalesApi_HUB)"],
      ["Retrieved", retrievedAt],
      ["Calculation", "Sales Orders = DISTINCT SalesOrder"],
      ["Item records", records.length],
      ...view.kpis.map((kpi) => [kpi.label, kpi.value] as Array<string | number>),
      ...(view.bullets ?? []).map((bullet, index) => [`Observation ${index + 1}`, bullet] as Array<string | number>),
      ...(view.note ? [["Notes", view.note] as Array<string | number>] : []),
    ],
  };
  const sheets = [summary, orderSheet(records), itemSheet(records), trendSheet(records)];
  if (view.rows.length > 0) sheets.splice(1, 0, { name: "Result", columns: view.columns, rows: view.rows });
  const csv: ExportSheet = view.rows.length > 0 ? { name: "Result", columns: view.columns, rows: view.rows } : sheets.find((sheet) => sheet.name === "Sales Orders")!;
  return { title: view.title, period, source: "SAP Sales API", retrievedAt, kpis: view.kpis, bullets: view.bullets ?? [], note: view.note, tables, sheets, csv };
}

export function registerExport(doc: ExportDocument): string {
  const now = Date.now();
  for (const [id, entry] of store) if (entry.expires <= now) store.delete(id);
  while (store.size >= MAX_EXPORTS) store.delete(store.keys().next().value as string);
  const id = randomUUID();
  store.set(id, { doc, expires: now + EXPORT_TTL_MS });
  return id;
}

export function getExport(id: string): ExportDocument | null {
  const entry = store.get(id);
  if (!entry || entry.expires <= Date.now()) {
    store.delete(id);
    return null;
  }
  return entry.doc;
}

export function exportFileName(doc: ExportDocument, format: ExportFormat): string {
  const slug = doc.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "sales";
  return `${slug}.${format}`;
}

// ---------- CSV ----------

function csvCell(value: string | number): string {
  const text = String(value ?? "");
  const safe = /^[=+\-@]/.test(text) && !/^-?\d/.test(text) ? `'${text}` : text;
  return /[",\n\r]/.test(safe) ? `"${safe.replace(/"/g, '""')}"` : safe;
}

export function toCsv(sheet: ExportSheet): Buffer {
  const lines = [sheet.columns, ...sheet.rows].map((row) => row.map(csvCell).join(","));
  return Buffer.from(`\uFEFF${lines.join("\r\n")}\r\n`, "utf8");
}

// ---------- XLSX (deflated zip, inline strings) ----------

const CRC_TABLE = (() => {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n += 1) {
    let c = n;
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c >>> 0;
  }
  return table;
})();

function crc32(buffer: Buffer): number {
  let crc = 0xffffffff;
  for (const byte of buffer) crc = CRC_TABLE[(crc ^ byte) & 0xff] ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}

function zip(files: Array<{ name: string; data: Buffer }>): Buffer {
  const locals: Buffer[] = [];
  const centrals: Buffer[] = [];
  let offset = 0;
  for (const file of files) {
    const name = Buffer.from(file.name, "utf8");
    const crc = crc32(file.data);
    const packed = deflateRawSync(file.data);
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(0x0800, 6);
    local.writeUInt16LE(8, 8);
    local.writeUInt32LE(0, 10);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(packed.length, 18);
    local.writeUInt32LE(file.data.length, 22);
    local.writeUInt16LE(name.length, 26);
    local.writeUInt16LE(0, 28);
    locals.push(local, name, packed);

    const central = Buffer.alloc(46);
    central.writeUInt32LE(0x02014b50, 0);
    central.writeUInt16LE(20, 4);
    central.writeUInt16LE(20, 6);
    central.writeUInt16LE(0x0800, 8);
    central.writeUInt16LE(8, 10);
    central.writeUInt32LE(0, 12);
    central.writeUInt32LE(crc, 16);
    central.writeUInt32LE(packed.length, 20);
    central.writeUInt32LE(file.data.length, 24);
    central.writeUInt16LE(name.length, 28);
    central.writeUInt32LE(offset, 42);
    centrals.push(central, name);
    offset += 30 + name.length + packed.length;
  }
  const centralSize = centrals.reduce((sum, part) => sum + part.length, 0);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(files.length, 8);
  end.writeUInt16LE(files.length, 10);
  end.writeUInt32LE(centralSize, 12);
  end.writeUInt32LE(offset, 16);
  return Buffer.concat([...locals, ...centrals, end]);
}

function xml(text: string): string {
  return text.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g, "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function columnName(index: number): string {
  let name = "";
  for (let n = index + 1; n > 0; n = Math.floor((n - 1) / 26)) name = String.fromCharCode(65 + ((n - 1) % 26)) + name;
  return name;
}

function sheetXml(sheet: ExportSheet): string {
  const rows = [sheet.columns, ...sheet.rows].map((row, rowIndex) => {
    const cells = row.map((value, colIndex) => {
      const ref = `${columnName(colIndex)}${rowIndex + 1}`;
      const style = rowIndex === 0 ? ' s="1"' : "";
      if (typeof value === "number" && Number.isFinite(value)) return `<c r="${ref}"${style}><v>${value}</v></c>`;
      return `<c r="${ref}" t="inlineStr"${style}><is><t xml:space="preserve">${xml(String(value ?? ""))}</t></is></c>`;
    });
    return `<row r="${rowIndex + 1}">${cells.join("")}</row>`;
  });
  const widths = sheet.columns.map((_, index) => `<col min="${index + 1}" max="${index + 1}" width="${index === 0 ? 22 : 16}" customWidth="1"/>`).join("");
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${widths}</cols><sheetData>${rows.join("")}</sheetData></worksheet>`;
}

export function toXlsx(sheets: ExportSheet[]): Buffer {
  const names = sheets.map((sheet, index) => xml(sheet.name.replace(/[\\/?*[\]:]/g, " ").slice(0, 31) || `Sheet${index + 1}`));
  const files = [
    {
      name: "[Content_Types].xml",
      data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_, index) => `<Override PartName="/xl/worksheets/sheet${index + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join("")}</Types>`,
    },
    {
      name: "_rels/.rels",
      data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,
    },
    {
      name: "xl/workbook.xml",
      data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${names.map((name, index) => `<sheet name="${name}" sheetId="${index + 1}" r:id="rId${index + 1}"/>`).join("")}</sheets></workbook>`,
    },
    {
      name: "xl/_rels/workbook.xml.rels",
      data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_, index) => `<Relationship Id="rId${index + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${index + 1}.xml"/>`).join("")}<Relationship Id="rId${sheets.length + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`,
    },
    {
      name: "xl/styles.xml",
      data: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE0E7FF"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/></cellXfs></styleSheet>`,
    },
    ...sheets.map((sheet, index) => ({ name: `xl/worksheets/sheet${index + 1}.xml`, data: sheetXml(sheet) })),
  ];
  return zip(files.map((file) => ({ name: file.name, data: Buffer.from(file.data, "utf8") })));
}

// ---------- PDF (Helvetica, WinAnsi, multi-page, tables) ----------

const PAGE_W = 595;
const PAGE_H = 842;
const MARGIN = 40;

function pdfText(value: string): string {
  return value
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/\u00b7/g, "-")
    .replace(/\u2026/g, "...")
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201c\u201d]/g, '"')
    .replace(/[^\x20-\x7e]/g, "")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

function fit(value: string, width: number, size: number): string {
  const max = Math.max(3, Math.floor(width / (size * 0.52)));
  return value.length > max ? `${value.slice(0, max - 2)}..` : value;
}

function wrap(value: string, width: number, size: number): string[] {
  const max = Math.max(10, Math.floor(width / (size * 0.5)));
  const words = value.split(/\s+/);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    if ((line + " " + word).trim().length > max) {
      if (line) lines.push(line);
      line = word;
    } else line = (line + " " + word).trim();
  }
  if (line) lines.push(line);
  return lines;
}

class PdfPages {
  pages: string[][] = [[]];
  y = PAGE_H - MARGIN;

  private get ops(): string[] {
    return this.pages[this.pages.length - 1];
  }

  ensure(height: number): void {
    if (this.y - height < MARGIN + 20) {
      this.pages.push([]);
      this.y = PAGE_H - MARGIN;
    }
  }

  text(value: string, x: number, size: number, bold = false, color = "0.12 0.16 0.23"): void {
    this.ops.push(`BT ${color} rg /${bold ? "F2" : "F1"} ${size} Tf ${x.toFixed(1)} ${this.y.toFixed(1)} Td (${pdfText(value)}) Tj ET`);
  }

  rect(x: number, y: number, w: number, h: number, color: string): void {
    this.ops.push(`${color} rg ${x.toFixed(1)} ${y.toFixed(1)} ${w.toFixed(1)} ${h.toFixed(1)} re f`);
  }

  paragraph(value: string, size = 10, indent = 0): void {
    for (const line of wrap(value, PAGE_W - 2 * MARGIN - indent, size)) {
      this.ensure(size + 4);
      this.text(line, MARGIN + indent, size);
      this.y -= size + 4;
    }
  }

  heading(value: string): void {
    this.ensure(40);
    this.y -= 8;
    this.text(value, MARGIN, 13, true, "0.26 0.22 0.79");
    this.y -= 18;
  }

  table(columns: string[], rows: string[][]): void {
    const width = PAGE_W - 2 * MARGIN;
    const size = columns.length > 6 ? 7 : 8;
    // Column widths follow content length so multi-currency amounts are not cut off.
    const weights = columns.map((column, index) => {
      const longest = Math.max(column.length, ...rows.slice(0, 200).map((row) => String(row[index] ?? "").length));
      return Math.min(60, Math.max(6, longest));
    });
    const totalWeight = weights.reduce((sum, weight) => sum + weight, 0);
    const widths = weights.map((weight) => (weight / totalWeight) * width);
    const lefts = widths.map((_, index) => MARGIN + widths.slice(0, index).reduce((sum, value) => sum + value, 0));
    const header = () => {
      this.ensure(34);
      this.rect(MARGIN, this.y - 4, width, 14, "0.88 0.91 1");
      columns.forEach((column, index) => this.text(fit(column, widths[index] - 4, size), lefts[index] + 2, size, true));
      this.y -= 15;
    };
    header();
    rows.forEach((row, rowIndex) => {
      if (this.y - 13 < MARGIN + 20) {
        this.ensure(1000);
        header();
      }
      if (rowIndex % 2 === 1) this.rect(MARGIN, this.y - 4, width, 13, "0.97 0.97 0.99");
      row.forEach((cell, index) => this.text(fit(String(cell ?? ""), widths[index] - 4, size), lefts[index] + 2, size));
      this.y -= 13;
    });
    this.y -= 6;
  }
}

export function toPdf(doc: ExportDocument): Buffer {
  const pdf = new PdfPages();
  pdf.rect(0, PAGE_H - 70, PAGE_W, 70, "0.31 0.27 0.9");
  pdf.y = PAGE_H - 38;
  pdf.text(doc.title, MARGIN, 17, true, "1 1 1");
  pdf.y -= 18;
  pdf.text(`Source: SAP Sales API (ZI_SalesApi_HUB)  |  Retrieved: ${doc.retrievedAt.replace("T", " ").slice(0, 19)} UTC`, MARGIN, 9, false, "0.9 0.92 1");
  pdf.y = PAGE_H - 96;

  if (doc.kpis.length > 0) {
    pdf.heading("Key figures");
    const perRow = doc.kpis.some((kpi) => kpi.value.length > 26) ? 2 : 3;
    const boxW = (PAGE_W - 2 * MARGIN - 6 * (perRow - 1)) / perRow;
    doc.kpis.forEach((kpi, index) => {
      if (index % perRow === 0) pdf.ensure(46);
      const x = MARGIN + (index % perRow) * (boxW + 6);
      const valueSize = Math.max(7, Math.min(10, (boxW - 10) / (Math.max(1, kpi.value.length) * 0.55)));
      pdf.rect(x, pdf.y - 26, boxW, 38, "0.95 0.96 1");
      pdf.text(fit(kpi.label, boxW - 10, 8), x + 6, 8, false, "0.4 0.45 0.55");
      const saved = pdf.y;
      pdf.y -= 16;
      pdf.text(fit(kpi.value, boxW - 10, valueSize), x + 6, valueSize, true);
      pdf.y = saved;
      if (index % perRow === perRow - 1 || index === doc.kpis.length - 1) pdf.y -= 46;
    });
  }
  if (doc.bullets.length > 0) {
    pdf.heading("Summary & observations");
    for (const bullet of doc.bullets) pdf.paragraph(`- ${bullet}`, 10, 4);
  }
  if (doc.note) {
    pdf.heading("Notes");
    pdf.paragraph(doc.note, 9);
  }
  for (const table of doc.tables) {
    pdf.heading(table.title);
    if (table.rows.length === 0) pdf.paragraph("Insufficient data to determine this.", 9);
    else pdf.table(table.columns, table.rows);
  }

  const total = pdf.pages.length;
  const objects: string[] = [];
  const pageIds: number[] = [];
  objects[1] = "<< /Type /Catalog /Pages 2 0 R >>";
  objects[3] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>";
  objects[4] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>";
  pdf.pages.forEach((ops, index) => {
    const footer = `BT 0.5 0.55 0.62 rg /F1 8 Tf ${MARGIN} 22 Td (${pdfText(`EVOLV AI Sales Analyst  |  ${doc.period}  |  Page ${index + 1} of ${total}`)}) Tj ET`;
    const stream = [...ops, footer].join("\n");
    const contentId = 5 + index * 2;
    const pageId = contentId + 1;
    objects[contentId] = `<< /Length ${Buffer.byteLength(stream, "latin1")} >>\nstream\n${stream}\nendstream`;
    objects[pageId] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_W} ${PAGE_H}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentId} 0 R >>`;
    pageIds.push(pageId);
  });
  objects[2] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageIds.length} >>`;

  let body = "%PDF-1.4\n";
  const offsets: number[] = [];
  for (let id = 1; id < objects.length; id += 1) {
    offsets[id] = Buffer.byteLength(body, "latin1");
    body += `${id} 0 obj\n${objects[id]}\nendobj\n`;
  }
  const xrefAt = Buffer.byteLength(body, "latin1");
  body += `xref\n0 ${objects.length}\n0000000000 65535 f \n`;
  for (let id = 1; id < objects.length; id += 1) body += `${String(offsets[id]).padStart(10, "0")} 00000 n \n`;
  body += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xrefAt}\n%%EOF`;
  return Buffer.from(body, "latin1");
}

export function renderExport(doc: ExportDocument, format: ExportFormat): { data: Buffer; contentType: string } {
  switch (format) {
    case "pdf":
      return { data: toPdf(doc), contentType: "application/pdf" };
    case "csv":
      return { data: toCsv(doc.csv), contentType: "text/csv; charset=utf-8" };
    case "xlsx":
      return { data: toXlsx(doc.sheets), contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" };
  }
}
